name: Lint Whiskers Repository

on:
  workflow_call:
    inputs:
      templates:
        required: true
        type: string
      whiskers-version:
        required: false
        type: string

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Setup Whiskers
        if: ${{ inputs.whiskers-version }}
        uses: catppuccin/setup-whiskers@feat/auto-detect
        with:
          whiskers-version: ${{ inputs.whiskers-version }}

      - name: Setup Whiskers (Auto Detecting Version)
        if: ${{ !inputs.whiskers-version }}
        uses: catppuccin/setup-whiskers@feat/auto-detect

      - name: Check Templates
        run: |
          FILES=$(echo "${{ inputs.templates }}" | grep -v "^$")
          while IFS= read -r file; do
            echo "::group::Checking $file"
            whiskers "$file" --check
            echo "::endgroup::"
          done <<< "$FILES"

